routes/admin.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/

Route::name('auth.')->prefix('auth')->group(function () {
    Route::name('login.')->prefix('login')->group(function () {
        Route::get('/', 'Auth\LoginController@showLoginForm')->name('index'); 
        Route::post('/', 'Auth\LoginController@login')->name('process');
    });

    Route::name('socials.')->prefix('socials')->group(function () {
        Route::get('/{platform}', 'Auth\LoginController@socialRedirect')->name('redirect'); 
        Route::get('/{platform}/callback', 'Auth\LoginController@socialCallback')->name('callback'); 
    }); 

    Route::name('register.')->prefix('register')->group(function () {
        Route::get('/', 'Auth\RegisterController@showRegistrationForm')->name('index'); 
        Route::post('/', 'Auth\RegisterController@register')->name('process'); 
    }); 

    Route::name('verification.')->prefix('verification')->group(function () {
        Route::get('/verify', 'Auth\VerificationController@verify')->name('verify')->middleware('auth'); 
        Route::get('/notice', 'Auth\VerificationController@show')->name('notice')->middleware('auth'); 
        Route::get('/resend', 'Auth\VerificationController@resend')->name('resend')->middleware('auth'); 
    }); 

    Route::name('logout')->get('logout', 'Auth\LoginController@logout')->middleware('auth'); 
}); 

Route::middleware('auth')->group(function () {
    Route::middleware('verified')->group(function () {
        Route::get('/', 'ProfileController@index')->name('index'); 

        Route::name('profile.')->prefix('profile')->group(function () {
            Route::get('/', 'ProfileController@index')->name('index'); 
            Route::put('/', 'ProfileController@update')->name('update'); 
        }); 

        Route::name('post.')->prefix('post')->group(function () {
            Route::get('/', 'PostController@index')->name('index'); 
            Route::get('/create', 'PostController@create')->name('create');
            Route::get('/{id}/edit', 'PostController@edit')->name('edit'); 
            Route::get('/tables', 'PostController@tables')->name('tables'); 
            Route::post('/', 'PostController@store')->name('store'); 
            Route::put('/', 'PostController@update')->name('update'); 
            Route::delete('/', 'PostController@delete')->name('delete'); 
        }); 
    
        Route::name('category.')->prefix('category')->group(function () {
            Route::get('/', 'CategoryController@index')->name('index'); 
            Route::get('/tables', 'CategoryController@tables')->name('tables'); 
            Route::post('/', 'CategoryController@store')->name('store'); 
            Route::put('/', 'CategoryController@update')->name('update'); 
            Route::delete('/', 'CategoryController@delete')->name('delete'); 
        }); 
        
        Route::middleware('role:Admin')->name('user.')->prefix('user')->group(function () {
            Route::get('/', 'UserController@index')->name('index'); 
            Route::get('/tables', 'UserController@tables')->name('tables'); 
            Route::post('/', 'UserController@store')->name('store'); 
            Route::put('/', 'UserController@update')->name('update'); 
            Route::delete('/', 'UserController@delete')->name('delete'); 
        }); 
    }); 
}); 

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@index')->name('index'); 
Route::get('/category/{slug}', 'CategoryController@index')->name('category'); 
Route::get('/post/{slug}', 'PostController@index')->name('post'); 

Route::get('/intagram/auth/callback', 'InstagramController@get');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Storage; 
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'google_id', 
        'facebook_id', 
        'avatar', 
        'email_verified_at', 
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class, 'user_id'); 
    }

    public function getAvatarUrlAttribute()
    {
        if ($this->avatar) {
            return Storage::disk('public')->url($this->avatar);
        }

        return config('app.default_avatar'); 
    }

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

resources/views/admin/profile.blade.php
@extends('admin::layouts.mainapp')

@section('title', 'My Profile')

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>My Profile</h1>
        </div>
        <div class="section-body">
            <div class="card profile-widget mt-5">
                <div class="profile-widget-header">
                    <img alt="image" src="{{ Auth::user()->avatar_url }}" class="rounded-circle profile-widget-picture">
                    <div class="profile-widget-items">
                        <div class="profile-widget-item">
                            <div class="profile-widget-item-label">Posts</div>
                            <div class="profile-widget-item-value">{{ Auth::user()->posts->count() }}</div>
                        </div>
                        <div class="profile-widget-item">
                        </div>
                        <div class="profile-widget-item">
                        </div>
                    </div>
                </div>
                <div class="profile-widget-description pb-0">
                    <div class="profile-widget-name">{{ Auth::user()->name }} <div class="text-muted d-inline font-weight-normal"><div class="slash"></div> {{ Auth::user()->roles[0]->name }}</div></div>
                    <div class="row">
                        <div class="col-lg-12">
                            <table class="table table-sm table-striped">
                                <tr>
                                    <th style="width:300px;">Email</th>
                                    <td> : {{ Auth::user()->email }}</td>
                                </tr>
                                <tr>
                                    <th>Registration Date</th>
                                    <td> : {{ date('F d, Y', strtotime(Auth::user()->created_at)) }}</td>
                                </tr>
                                <tr>
                                    <th>Connected Social Media</th>
                                    <td>
                                        :
                                        @if (Auth::user()->google_id)
                                            <span class="badge badge-danger">Google</span>
                                        @endif
                                        @if (Auth::user()->facebook_id)
                                            <span class="badge badge-primary">Facebook</span>
                                        @endif
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>    
                </div>
            </div>
            <div class="card">
                <form action="{{ route('admin.profile.update') }}" method="POST" onsubmit="doSubmit(this, event)">
                    @method('PUT')
                    @csrf
                    <div class="card-header">
                        <strong>Change Account Password</strong>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="">Old Password</label>
                            <input type="password" name="old_password" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="">New Password</label>
                            <input type="password" name="password" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="">Password Confirmation</label>
                            <input type="password" name="password_confirmation" class="form-control">
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-danger"> Reset Password </button>
                    </div>
                </form>
            </div>
        </div>
    </section>
@endsection

@push('scripts')
    <script>
        
        /**
		 * Submit Action
		 */
		const doSubmit = (element, event) => {
			event.preventDefault(); 
			$element = $(element); 
			$element.find('button[type="submit"]')
				.addClass('disabled')
				.attr('disabled', 'disabled')
				.html(`<i class="fa fw-fw fa-circle-notch fa-spin"></i> Sending data`); 

			axios({
				url: $element.attr('action'),
				method: $element.attr('method'), 
				data: $element.serialize(), 
			})
			.then(resultJson => {
				Swal.fire('Success', resultJson.data.message, 'success'); 
				$element.find('button[type="submit"]')
					.removeClass('disabled')
					.removeAttr('disabled')
					.html(`Save`); 
				resetInput().then(() => {
					modalForm.modal('hide'); 
				});
			})
			.catch(errorResponse => {
				handleErrorRequest(errorResponse);
				$element.find('button[type="submit"]')
					.removeClass('disabled')
					.removeAttr('disabled')
					.html(`Save`); 
			}); 
		}; 

    </script>
@endpush